global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mspr2-client-service'
    static_configs:
      - targets: ['client-service:3333']
    metrics_path: '/metrics'
    