name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

env:
  NODE_ENV: test
  PORT: 3333
  APP_KEY: ${{ secrets.APP_KEY }}
  HOST: 127.0.0.1
  LOG_LEVEL: info
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.DB_DATABASE }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.DB_USER }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Run tests inside Docker container
        env:
          NODE_ENV: ${{ env.NODE_ENV }}
          PORT: ${{ env.PORT }}
          APP_KEY: ${{ env.APP_KEY }}
          HOST: ${{ env.HOST }}
          LOG_LEVEL: ${{ env.LOG_LEVEL }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_DATABASE: ${{ env.DB_DATABASE }}
        run: |
          docker run --rm \
            -e NODE_ENV=$NODE_ENV \
            -e PORT=$PORT \
            -e APP_KEY=$APP_KEY \
            -e HOST=$HOST \
            -e LOG_LEVEL=$LOG_LEVEL \
            -e DB_HOST=$DB_HOST \
            -e DB_PORT=$DB_PORT \
            -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e DB_DATABASE=$DB_DATABASE \
            $IMAGE_NAME npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME
