name: CI Pipeline - Build & Test Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t client-service:ci .

      - name: Run tests inside Docker container
        run: |
          docker run --rm client-service:ci npm test
