name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }} # ex: monpseudo/client-service:latest

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Run tests inside Docker container
        run: |
          docker run --rm \
            -e NODE_ENV=test \
            -e PORT=${{ secrets.TEST_PORT }} \
            -e APP_KEY=${{ secrets.TEST_APP_KEY }} \
            -e HOST=${{ secrets.TEST_HOST }} \
            -e LOG_LEVEL=${{ secrets.TEST_LOG_LEVEL }} \
            $IMAGE_NAME npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME